export const products = [
  {
    id: 1,
    title: "Pedas Gurih Enak",
    description: "makanan dengan rasa pedas, gurih.",
    restaurants: [
      {
        id: 1,
        name: "Jhon Doe",
        img: require("../assets/img/categories/makanan.png"),
        description: "mie pedas nikmat",
        lng: "",
        lat: "",
        address: "Jakarta",
        stars: 5,
        reviews: "2.1k",
        category: "Cepat Saji",
        dishes: [
          {
            id: 1,
            name: "mie spesial",
            description: "mie pedas nikmat",
            price: 20000,
            image: require("../assets/img/categories/makanan.png"),
          },
          {
            id: 2,
            name: "Baso Gurih",
            description: "mie pedas nikmat",
            price: 20000,
            image: require("../assets/img/categories/makanan.png"),
          },
        ],
      },
      {
        id: 1,
        name: "Michael",
        img: require("../assets/img/categories/makanan.png"),
        description: "mie pedas nikmat",
        lng: "",
        lat: "",
        address: "Jakarta Selatan",
        stars: 5,
        reviews: "2.1k",
        category: "Cepat Saji",
        dishes: [
          {
            id: 1,
            name: "mie spesial",
            description: "mie pedas nikmat",
            price: 20000,
            image: require("../assets/img/categories/makanan.png"),
          },
          {
            id: 2,
            name: "Baso Gurih",
            description: "mie pedas nikmat",
            price: 20000,
            image: require("../assets/img/categories/makanan.png"),
          },
        ],
      },
    ],
  },
  {
    id: 1,
    title: "Minuman Segar Bikin Nagih",
    description: "Berbagai minuman yang bikin kamu tergoda.",
    restaurants: [
      {
        id: 1,
        name: "Jhon Doe",
        img: require("../assets/img/categories/minuman.jpg"),
        description: "mie pedas nikmat",
        lng: "",
        lat: "",
        address: "Jakarta",
        stars: 5,
        reviews: "2.1k",
        category: "Cepat Saji",
        dishes: [
          {
            id: 1,
            name: "mie spesial",
            description: "mie pedas nikmat",
            price: 20000,
            image: require("../assets/img/categories/makanan.png"),
          },
          {
            id: 2,
            name: "Baso Gurih",
            description: "mie pedas nikmat",
            price: 20000,
            image: require("../assets/img/categories/makanan.png"),
          },
        ],
      },
      {
        id: 1,
        name: "Michael",
        img: require("../assets/img/categories/minuman.jpg"),
        description: "mie pedas nikmat",
        lng: "",
        lat: "",
        address: "Jakarta Selatan",
        stars: 5,
        reviews: "2.1k",
        category: "Cepat Saji",
        dishes: [
          {
            id: 1,
            name: "mie spesial",
            description: "mie pedas nikmat",
            price: 20000,
            image: require("../assets/img/categories/makanan.png"),
          },
          {
            id: 2,
            name: "Baso Gurih",
            description: "mie pedas nikmat",
            price: 20000,
            image: require("../assets/img/categories/makanan.png"),
          },
        ],
      },
    ],
  },
];
